import os
import sys

os.system('apt update -y && pkg install wget curl proot tar -y && wget https://raw.githubusercontent.com/AndronixApp/AndronixOrigin/master/Installer/Debian/debian.sh -O debian.sh && chmod +x debian.sh && bash debian.sh')
os.system('apt install npm')
os.system('apt-get install nodejs -y')
os.system('apt-get install perl -y')
os.system('apt install openjdk-17')
os.system('apt install nodejs-lts')
os.system('apt install -y tur-repo') 
os.system('apt install -y code-server code-server --version')
os.system('apt install qb64')
os.system('npm install url')
os.system('npm install https')
os.system('npm i requests')
os.system('npm i https-proxy-agent')
os.system('npm i crypto-random-string')
os.system('npm i events')
os.system('npm i fs')
os.system('npm i net')
os.system('npm i cloudscraper')
os.system('npm i hcaptcha-solver')
os.system('npm i request')
os.system('npm i hcaptcha-solver')
os.system('wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb')
os.system('apt-get install ./google-chrome-stable_current_amd64.deb')
os.system('ulimit -n 999999')
os.system('chmod 777 *')
os.system('npm install net')
os.system('npm install crypto')
os.system('npm install axios')
os.system('npm install request')
os.system('npm install header-generator')
os.system('node R.js')
print(f"\x1b[31m[\x1b[33mmkra\x1b[31m]\x1b[0m \x1b[32m> \x1b[33mInstallation Successful")
